spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: SYSTEM
    password: HR
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true